In [10]:
import numpy as np
a=np.array([range(1,10) for i in range(3)])

(3, 9)

In [11]:
#число измерений
a.ndim

2

In [13]:
#размеры массива (кортеж)
a.shape

(3, 9)

In [16]:
#вектор-столбец
col=np.array([[1], [2], [3]])
col

array([[1],
       [2],
       [3]])

In [19]:
np.zeros((3,3),dtype='int')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [23]:
np.arange(0.1,0.5,0.1)

array([0.1, 0.2, 0.3, 0.4])

In [10]:
import numpy as np
a=np.arange(-1.3+(1.3+2.5)/64, 2.5-(1.3+2.5)/64, (1.3+2.5)/64)
a
# len(a)

array([-1.240625, -1.18125 , -1.121875, -1.0625  , -1.003125, -0.94375 ,
       -0.884375, -0.825   , -0.765625, -0.70625 , -0.646875, -0.5875  ,
       -0.528125, -0.46875 , -0.409375, -0.35    , -0.290625, -0.23125 ,
       -0.171875, -0.1125  , -0.053125,  0.00625 ,  0.065625,  0.125   ,
        0.184375,  0.24375 ,  0.303125,  0.3625  ,  0.421875,  0.48125 ,
        0.540625,  0.6     ,  0.659375,  0.71875 ,  0.778125,  0.8375  ,
        0.896875,  0.95625 ,  1.015625,  1.075   ,  1.134375,  1.19375 ,
        1.253125,  1.3125  ,  1.371875,  1.43125 ,  1.490625,  1.55    ,
        1.609375,  1.66875 ,  1.728125,  1.7875  ,  1.846875,  1.90625 ,
        1.965625,  2.025   ,  2.084375,  2.14375 ,  2.203125,  2.2625  ,
        2.321875,  2.38125 ])

In [21]:
import numpy as np
a=np.array([], dtype=int)
n=int(input('Input n: '))
np.append(a, [1, 2, 3]*n**2)[:3*n]

#2 вариант
#import numpy as np
#n=int(input('Input n: '))
# np.array([1,2,3]*n)

Input n: 12


array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1,
       2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [7]:
import numpy as np
a=np.zeros((10,10))
a[[0,-1]], a[:,[0,-1]] = 1, 1
# a[:,[0,-1]]=1
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [17]:
import numpy as np
a=np.tile([[0,1], [1,0]],[4,4])
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [28]:
import numpy as np
np.dot(2,2) #умножение скаляров

np.dot(2,np.array([5,4,3,2,1])) #произведение вектора и скаляра

A=np.arange(10)
B=np.arange(4,14)
C=np.random.randint(10, size=(10,10))
D=np.random.randint(10, size=(10,10))

np.dot(A,B) #скалярное произведение

np.dot(A,C) # умножение матриц

np.dot(C,D) #умножение матриц

array([[126, 198, 202, 141, 234, 181, 156, 233, 196, 220],
       [223, 200, 304, 193, 237, 172, 192, 273, 249, 243],
       [172, 167, 273, 159, 196, 163, 167, 241, 226, 230],
       [105, 166, 244, 139, 227, 207, 168, 272, 215, 263],
       [229, 253, 272, 214, 281, 195, 212, 280, 276, 258],
       [251, 220, 302, 223, 251, 154, 208, 285, 246, 242],
       [236, 240, 311, 210, 251, 230, 223, 317, 251, 300],
       [210, 204, 285, 205, 196, 187, 176, 231, 256, 249],
       [266, 254, 356, 240, 255, 250, 240, 359, 251, 314],
       [153, 140, 202, 147, 259, 117, 166, 220, 219, 203]])

In [48]:
import numpy as np
import pandas as pd

s=np.sin(np.arange(0,1,0.05))

c=np.cos(np.arange(0,1,0.05))

df=pd.DataFrame({'sin': s, 'cos': c}, index=np.arange(0,1,0.05))
df

sin       cos
0.00  0.000000  1.000000
0.05  0.049979  0.998750
0.10  0.099833  0.995004
0.15  0.149438  0.988771
0.20  0.198669  0.980067
0.25  0.247404  0.968912
0.30  0.295520  0.955336
0.35  0.342898  0.939373
0.40  0.389418  0.921061
0.45  0.434966  0.900447
0.50  0.479426  0.877583
0.55  0.522687  0.852525
0.60  0.564642  0.825336
0.65  0.605186  0.796084
0.70  0.644218  0.764842
0.75  0.681639  0.731689
0.80  0.717356  0.696707
0.85  0.751280  0.659983
0.90  0.783327  0.621610
0.95  0.813416  0.581683

In [51]:
import numpy as np
np.random.rand(3,5)

array([[0.42238091, 0.44503318, 0.846327  , 0.7260353 , 0.76396204],
       [0.63981997, 0.8759356 , 0.78109735, 0.95937773, 0.48737038],
       [0.01351812, 0.6278712 , 0.74718675, 0.66222775, 0.06340399]])

In [61]:
import numpy as np
a=np.array([[1,2,3],[3,4,5],[6,7,8]])
a.sum(axis=0) #сумма по столбцам
a.sum(axis=1) #сумма по строкам
a.sum() #сумма всех элементов
a.mean(axis=1) #построчное среднее значение
a.var(axis=1) # построчная дисперсия
a.std(axis=1) #построчное стандартное отклонение

array([0.66666667, 0.66666667, 0.66666667])

In [2]:
import numpy as np
a=np.random.randint(10, size=(3,3))
(a-a.mean(axis=1)) / a.std(axis=1)

array([[ 1.37281295, -2.74562589, -2.59554274],
       [ 3.13785816, -0.39223227, -1.62221421],
       [ 2.54950976, -0.39223227,  1.29777137]])

In [23]:
import numpy as np

a=np.random.randint(10, size=(3,3))
print("Input array:", a, sep='\n')

a[:, 2]=a[:, 2][np.argsort(a[:, 2])]
print("New array:", a, sep='\n')

Input array:
[[7 1 2]
 [9 8 8]
 [2 6 7]]
New array:
[[7 1 2]
 [9 8 7]
 [2 6 8]]


In [38]:
import numpy as np

A=np.random.randint(10, size=(4,5))
print("Matrix A:", A, sep='\n', end='\n\n')

B=np.dot(A.T, A)
print("Matrix B:", B, sep='\n', end='\n'*2)

C=np.dot(A, A.T)
print("Matrix С:", C, sep='\n', end='\n'*2)

print('матрицы равны' if (B.shape==C.shape and B==C) else 'матрицы не равны')

Matrix A:
[[2 7 8 2 2]
 [6 3 7 6 0]
 [5 4 6 6 9]
 [4 9 2 5 1]]

Matrix B:
[[ 81  88  96  90  53]
 [ 88 155 119 101  59]
 [ 96 119 153 104  72]
 [ 90 101 104 101  63]
 [ 53  59  72  63  86]]

Matrix С:
[[125 101 116  99]
 [101 130 120  95]
 [116 120 194 107]
 [ 99  95 107 127]]

матрицы не равны


In [42]:
import numpy as np

A=np.random.randint(10, size=(5,5))
B=np.random.randint(10, size=(5,5))
print(A)
np.diag(A)+np.diag(B)

array([ 5, 12, 15, 10, 11])

In [10]:
import numpy as np

A=np.random.randint(10, size=(3,3))
print(A)
print(f"Определитель A: {int(np.linalg.det(A))}", end='\n'*2)
print(f"Ранг матрицы A: {np.linalg.matrix_rank(A)}", end='\n'*2)
print(f"Спектр матрицы:\n {np.linalg.inv(A)}")

[[1 0 1]
 [9 8 5]
 [6 0 3]]
Определитель A: -24

Ранг матрицы A: 3

Спектр матрицы:
 [[-1.          0.          0.33333333]
 [-0.125       0.125      -0.16666667]
 [ 2.          0.         -0.33333333]]


In [24]:
import numpy as np

def foo(x):
    return (x**2+3)/(x-2)

def create_array(a,b):
    return np.arange(a,b,0.01)

def main():
    try:
        a,b=map(int, input("Введите пределы интегрирования: ").split())
    except:
        print("Некорректно-введенные ")
    else:
        print(f"Примерное значение интеграла: {foo(create_array(a,b)).sum()}")

# a=create_array(1,2)
# foo(a).sum()
main()

Введите пределы интегрирования: 1 2
Примерное значение интеграла: -3281.6642623478324
